name: pr_notify

on:
  pull_request:
    branches:
      - main

jobs:
  sendMessage:
    name: ĞÑ‚Ğ¿Ñ€Ğ°Ğ²ĞºĞ° ÑĞ±Ñ‰. Ğ¾ PR Ğ² Ñ‡Ğ°Ñ‚ Telegram
    runs-on: ubuntu-latest
    steps:
      - name: ĞÑ‚Ğ¿Ñ€Ğ°Ğ²ĞºĞ° ÑĞ±Ñ‰.
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_GROUP }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          format: markdown
          photo: /.github/logo.png
          message: |
            ğŸ“¥ **ĞĞ¾Ğ²Ñ‹Ğ¹ Pull Request!**
            ğŸ‘¨â€ğŸ’» [${{ github.actor }}](https://github.com/${{ github.actor }}) / telegram: @${{ github.actor }}
            ğŸ—‚ [${{ github.repository }}](https://github.com/${{ github.repository }}/pulls)
            ğŸ¤– ${{github.workflow}}